/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    name: string;
    address?: string;
}
export interface TripWithEvents {
    trip: Trip;
    events: Array<Event>;
}
export interface Profile {
    name: string;
}
export interface Trip {
    id: bigint;
    destination?: string;
    endDate?: bigint;
    name: string;
    createdAt: bigint;
    shareToken: string;
    startDate?: bigint;
}
export interface Event {
    id: bigint;
    title: string;
    confirmationCode?: string;
    createdAt: bigint;
    tripId: bigint;
    notes?: string;
    dateTime: bigint;
    location: Location;
    eventType: EventType;
}
export enum EventType {
    Flight = "Flight",
    Hotel = "Hotel",
    Activity = "Activity"
}
export interface backendInterface {
    createEvent(tripId: bigint, eventType: EventType, title: string, dateTime: bigint, location: Location, confirmationCode: string | null, notes: string | null): Promise<bigint>;
    createTrip(name: string, destination: string | null, startDate: bigint | null, endDate: bigint | null): Promise<bigint>;
    deleteEvent(id: bigint): Promise<void>;
    deleteTrip(id: bigint): Promise<void>;
    getEvents(tripId: bigint): Promise<Array<Event>>;
    getProfile(): Promise<Profile | null>;
    getSharedTrip(shareToken: string): Promise<TripWithEvents | null>;
    getTripById(id: bigint): Promise<TripWithEvents | null>;
    getTrips(): Promise<Array<Trip>>;
    setProfile(name: string): Promise<void>;
    updateEvent(id: bigint, eventType: EventType, title: string, dateTime: bigint, location: Location, confirmationCode: string | null, notes: string | null): Promise<void>;
    updateTrip(id: bigint, name: string, destination: string | null, startDate: bigint | null, endDate: bigint | null): Promise<void>;
}
import type { Event as _Event, EventType as _EventType, Location as _Location, Profile as _Profile, Trip as _Trip, TripWithEvents as _TripWithEvents } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createEvent(arg0: bigint, arg1: EventType, arg2: string, arg3: bigint, arg4: Location, arg5: string | null, arg6: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_Location_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_Location_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createTrip(arg0: string, arg1: string | null, arg2: bigint | null, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getEvents(arg0: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedTrip(arg0: string): Promise<TripWithEvents | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedTrip(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedTrip(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTripById(arg0: bigint): Promise<TripWithEvents | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrips();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrips();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: EventType, arg2: string, arg3: bigint, arg4: Location, arg5: string | null, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_Location_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_EventType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_Location_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateTrip(arg0: bigint, arg1: string, arg2: string | null, arg3: bigint | null, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_EventType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TripWithEvents_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripWithEvents): TripWithEvents {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TripWithEvents]): TripWithEvents | null {
    return value.length === 0 ? null : from_candid_TripWithEvents_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    address: [] | [string];
}): {
    name: string;
    address?: string;
} {
    return {
        name: value.name,
        address: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.address))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trip: _Trip;
    events: Array<_Event>;
}): {
    trip: Trip;
    events: Array<Event>;
} {
    return {
        trip: from_candid_Trip_n19(_uploadFile, _downloadFile, value.trip),
        events: from_candid_vec_n7(_uploadFile, _downloadFile, value.events)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    destination: [] | [string];
    endDate: [] | [bigint];
    name: string;
    createdAt: bigint;
    shareToken: string;
    startDate: [] | [bigint];
}): {
    id: bigint;
    destination?: string;
    endDate?: bigint;
    name: string;
    createdAt: bigint;
    shareToken: string;
    startDate?: bigint;
} {
    return {
        id: value.id,
        destination: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.destination)),
        endDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.endDate)),
        name: value.name,
        createdAt: value.createdAt,
        shareToken: value.shareToken,
        startDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.startDate))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    confirmationCode: [] | [string];
    createdAt: bigint;
    tripId: bigint;
    notes: [] | [string];
    dateTime: bigint;
    location: _Location;
    eventType: _EventType;
}): {
    id: bigint;
    title: string;
    confirmationCode?: string;
    createdAt: bigint;
    tripId: bigint;
    notes?: string;
    dateTime: bigint;
    location: Location;
    eventType: EventType;
} {
    return {
        id: value.id,
        title: value.title,
        confirmationCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.confirmationCode)),
        createdAt: value.createdAt,
        tripId: value.tripId,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        dateTime: value.dateTime,
        location: from_candid_Location_n11(_uploadFile, _downloadFile, value.location),
        eventType: from_candid_EventType_n13(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Flight: null;
} | {
    Hotel: null;
} | {
    Activity: null;
}): EventType {
    return "Flight" in value ? EventType.Flight : "Hotel" in value ? EventType.Hotel : "Activity" in value ? EventType.Activity : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n8(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Location_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location): _Location {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    address?: string;
}): {
    name: string;
    address: [] | [string];
} {
    return {
        name: value.name,
        address: value.address ? candid_some(value.address) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    Flight: null;
} | {
    Hotel: null;
} | {
    Activity: null;
} {
    return value == EventType.Flight ? {
        Flight: null
    } : value == EventType.Hotel ? {
        Hotel: null
    } : value == EventType.Activity ? {
        Activity: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
