/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventType = IDL.Variant({
  'Flight' : IDL.Null,
  'Hotel' : IDL.Null,
  'Activity' : IDL.Null,
});
export const Location = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'confirmationCode' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'tripId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'dateTime' : IDL.Int,
  'location' : Location,
  'eventType' : EventType,
});
export const Profile = IDL.Record({ 'name' : IDL.Text });
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Opt(IDL.Text),
  'endDate' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'shareToken' : IDL.Text,
  'startDate' : IDL.Opt(IDL.Int),
});
export const TripWithEvents = IDL.Record({
  'trip' : Trip,
  'events' : IDL.Vec(Event),
});

export const idlService = IDL.Service({
  'createEvent' : IDL.Func(
      [
        IDL.Nat,
        EventType,
        IDL.Text,
        IDL.Int,
        Location,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createTrip' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteTrip' : IDL.Func([IDL.Nat], [], []),
  'getEvents' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getSharedTrip' : IDL.Func([IDL.Text], [IDL.Opt(TripWithEvents)], ['query']),
  'getTripById' : IDL.Func([IDL.Nat], [IDL.Opt(TripWithEvents)], ['query']),
  'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        EventType,
        IDL.Text,
        IDL.Int,
        Location,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateTrip' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventType = IDL.Variant({
    'Flight' : IDL.Null,
    'Hotel' : IDL.Null,
    'Activity' : IDL.Null,
  });
  const Location = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'confirmationCode' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'tripId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'dateTime' : IDL.Int,
    'location' : Location,
    'eventType' : EventType,
  });
  const Profile = IDL.Record({ 'name' : IDL.Text });
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Opt(IDL.Text),
    'endDate' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'shareToken' : IDL.Text,
    'startDate' : IDL.Opt(IDL.Int),
  });
  const TripWithEvents = IDL.Record({
    'trip' : Trip,
    'events' : IDL.Vec(Event),
  });
  
  return IDL.Service({
    'createEvent' : IDL.Func(
        [
          IDL.Nat,
          EventType,
          IDL.Text,
          IDL.Int,
          Location,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createTrip' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteTrip' : IDL.Func([IDL.Nat], [], []),
    'getEvents' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getSharedTrip' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TripWithEvents)],
        ['query'],
      ),
    'getTripById' : IDL.Func([IDL.Nat], [IDL.Opt(TripWithEvents)], ['query']),
    'getTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          EventType,
          IDL.Text,
          IDL.Int,
          Location,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateTrip' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };