/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'title' : string,
  'confirmationCode' : [] | [string],
  'createdAt' : bigint,
  'tripId' : bigint,
  'notes' : [] | [string],
  'dateTime' : bigint,
  'location' : Location,
  'eventType' : EventType,
}
export type EventType = { 'Flight' : null } |
  { 'Hotel' : null } |
  { 'Activity' : null };
export interface Location { 'name' : string, 'address' : [] | [string] }
export interface Profile { 'name' : string }
export interface Trip {
  'id' : bigint,
  'destination' : [] | [string],
  'endDate' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'shareToken' : string,
  'startDate' : [] | [bigint],
}
export interface TripWithEvents { 'trip' : Trip, 'events' : Array<Event> }
export interface _SERVICE {
  'createEvent' : ActorMethod<
    [bigint, EventType, string, bigint, Location, [] | [string], [] | [string]],
    bigint
  >,
  'createTrip' : ActorMethod<
    [string, [] | [string], [] | [bigint], [] | [bigint]],
    bigint
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteTrip' : ActorMethod<[bigint], undefined>,
  'getEvents' : ActorMethod<[bigint], Array<Event>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getSharedTrip' : ActorMethod<[string], [] | [TripWithEvents]>,
  'getTripById' : ActorMethod<[bigint], [] | [TripWithEvents]>,
  'getTrips' : ActorMethod<[], Array<Trip>>,
  'setProfile' : ActorMethod<[string], undefined>,
  'updateEvent' : ActorMethod<
    [bigint, EventType, string, bigint, Location, [] | [string], [] | [string]],
    undefined
  >,
  'updateTrip' : ActorMethod<
    [bigint, string, [] | [string], [] | [bigint], [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];